# -*- coding: utf-8 -*-
"""Another copy of healthcare-risk-ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6QxbvLF2BWHVBqBaErwxnKpBYgPqu5Y
"""

# Project Title
# Healthcare Risk Prediction using Machine Learning
# Description
# This project uses a logistic regression model to predict diabetes risk based on patient health indicators. The goal is to demonstrate how machine learning can be applied to healthcare data to support early detection and risk assessment.


# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Step 2: Load dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness",
           "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]

df = pd.read_csv(url, names=columns)

print("First 5 rows:")
print(df.head())

# Step 3: Define features and target
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

# Step 4: Train/Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Step 6: Predictions
y_pred = model.predict(X_test)

# Step 7: Evaluate
accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nDataset Info:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("\nImproved Accuracy:", accuracy_score(y_test, y_pred))

import matplotlib.pyplot as plt

df.hist(figsize=(10,8))
plt.show()